apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wikijs-mariadb-pvc
  labels:
    app: wikijs
spec:
  storageClassName: storageName
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
