apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb-wikijs
  labels:
    app: wikijs
    tier: mysql
spec:
  selector:
    matchLabels:
      app: wikijs
      tier: mysql
  serviceName: mariadb-service
  template:
    metadata:
      labels:
        app: wikijs
        tier: mysql
    spec:
      containers:
      - image: mariadb:10.5
        name: mariadb
        env:
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              key: mysql-user
              name: mariadb-configmap
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: mysql-root-passwd
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              key: mysql-database
              name: mariadb-configmap
        ports:
        - containerPort: 3306
          name: wikijs-mariadb
        volumeMounts:
        - name: wikijs-mariadb-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: wikijs-mariadb-persistent-storage
        persistentVolumeClaim:
          claimName: wikijs-mariadb-pvc
