apiVersion: v1
kind: Service
metadata:
  name: wikijs-service
  labels:
    app: wikijs
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: wikijs
    tier: frontend
  type: ClusterIP
